### ISSUE TITLE
Release 1.0.0

### ISSUE THREAD

**Issue by arjunrajeev** [arjunrajeev/Core-Framework#7]
Release 1.0.0 will cover the following issues

- [x] #1 New Expected Conditions
- [x] #2 Add Readme file
- [x] #3 Expand Abstract Page
- [x] #4 Expand Find Class
- [x] #5 Stream line abstract test
- [x] #6 Move Log to common package
- [x] #13 Modify loggers
